import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    formAssistant: "Smart Form Assistant",
    rfeDecoder: "RFE Decoder",
    strategy: "Strategy Advisor",
    marketplace: "Expert Marketplace",
    welcome: "Welcome back, Mateo",
    managing: "Managing your I-130 Petition for Alien Relative",
    caseTimeline: "Case Timeline Tracker",
    onTrack: "On Track",
    waitNormal: "Is my wait time normal?",
    dontWorry: "Don't Worry: Your case is proceeding normally.",
    daysPending: "You have been waiting {days} days.",
    quickActions: "Quick Actions",
    continueForm: "Continue Form I-130",
    formDesc: "Complete your petition with AI-powered error checking.",
    rfeTitle: "Received an RFE?",
    rfeDesc: "Upload your USCIS letter. Our AI will decode it.",
    stratTitle: "Strategic Advisor",
    stratDesc: "Unsure about next steps? Ask our AI strategist.",
    marketTitle: "Find an Attorney",
    marketDesc: "Connect with vetted experts for your specific case.",
    signOut: "Sign Out",
    profile: "Profile",
    supportAgent: "ImmiGuide Support",
    online: "Online",
    typeMessage: "Type a message...",
    uploadDoc: "Upload Document (PDF/Img)",
    pasteRfe: "Paste RFE Text Here",
    analyzeNow: "Analyze Now",
    decoding: "Decoding...",
    highSeverity: "High Severity Case Detected",
    highSeverityDesc: "This RFE indicates a significant risk. We recommend consulting the Strategy Advisor.",
    draftResponse: "Draft Legal Response Letter",
    requiredEvidence: "Required Evidence",
    actionPlan: "Action Plan",
    saveContinue: "Save & Continue",
    whereLived: "Where have you lived?",
    physAddress: "Physical Address History",
    aiHelper: "ImmiGuide Smart Assistant",
    analyzeField: "Analyzing field context...",
    focusField: "Focus on a field to see tailored advice.",
    whatMean: "What does this mean?",
    commonTraps: "Common Traps",
    exampleAns: "Example Answer",
    formHealth: "Form Health",
    fieldsCompleted: "Fields Completed",
    validationErrors: "Validation Errors",
    strategyIntro: "Hello! I'm your immigration strategy advisor. I can help you compare visa types, understand timelines, or decide on next steps.",
    strategyPlaceholder: "Ask about K-1 vs CR-1, processing times, or travel risks...",
    supportIntro: "Hi! I'm your ImmiGuide support agent. How can I help you today?",
    changeDoc: "Change Document",
    removeFile: "Remove File",
    yourRfeContent: "Your RFE Content",
    fileSelected: "File Selected",
    analysisComplete: "Analysis Complete",
    responseDraft: "Response Draft",
    disclaimer: "Always have a licensed attorney review this document.",
    strategyDisclaimer: "ImmiGuide can make mistakes. Please verify important information with an attorney.",
    caseNumber: "Case Number",
    findExpert: "Find an Expert",
    filterSpecialty: "Filter by Specialty",
    filterLanguage: "Filter by Language",
    verifiedExpert: "Verified Expert",
    successRate: "Success Rate",
    reviews: "reviews",
    startsAt: "Starts at",
    bookConsult: "Book Free 15-min Consult",
    rfeMatch: "Recommended for your RFE",
    nextAvailable: "Next available",
    allSpecialties: "All Specialties",
    allLanguages: "All Languages"
  },
  es: {
    dashboard: "Panel Principal",
    formAssistant: "Asistente de Formulario",
    rfeDecoder: "Decodificador RFE",
    strategy: "Asesor de Estrategia",
    marketplace: "Mercado de Expertos",
    welcome: "Bienvenido de nuevo, Mateo",
    managing: "Gestionando tu Petición I-130 para Familiar Extranjero",
    caseTimeline: "Rastreador de Caso",
    onTrack: "En Camino",
    waitNormal: "¿Es normal mi tiempo de espera?",
    dontWorry: "No te preocupes: Tu caso avanza normalmente.",
    daysPending: "Has estado esperando {days} días.",
    quickActions: "Acciones Rápidas",
    continueForm: "Continuar Formulario I-130",
    formDesc: "Completa tu petición con verificación de errores por IA.",
    rfeTitle: "¿Recibiste un RFE?",
    rfeDesc: "Sube tu carta de USCIS. Nuestra IA la decodificará.",
    stratTitle: "Asesor Estratégico",
    stratDesc: "¿Inseguro sobre los siguientes pasos? Pregunta a nuestra IA.",
    marketTitle: "Encontrar Abogado",
    marketDesc: "Conecta con expertos verificados para tu caso.",
    signOut: "Cerrar Sesión",
    profile: "Perfil",
    supportAgent: "Soporte ImmiGuide",
    online: "En línea",
    typeMessage: "Escribe un mensaje...",
    uploadDoc: "Subir Documento (PDF/Img)",
    pasteRfe: "Pega el texto del RFE aquí",
    analyzeNow: "Analizar Ahora",
    decoding: "Decodificando...",
    highSeverity: "Caso de Alta Gravedad Detectado",
    highSeverityDesc: "Este RFE indica un riesgo significativo. Recomendamos consultar al Asesor de Estrategia.",
    draftResponse: "Redactar Respuesta Legal",
    requiredEvidence: "Evidencia Requerida",
    actionPlan: "Plan de Acción",
    saveContinue: "Guardar y Continuar",
    whereLived: "¿Dónde has vivido?",
    physAddress: "Historial de Dirección Física",
    aiHelper: "Asistente Inteligente ImmiGuide",
    analyzeField: "Analizando contexto...",
    focusField: "Enfoca un campo para ver consejos.",
    whatMean: "¿Qué significa esto?",
    commonTraps: "Trampas Comunes",
    exampleAns: "Ejemplo de Respuesta",
    formHealth: "Salud del Formulario",
    fieldsCompleted: "Campos Completados",
    validationErrors: "Errores de Validación",
    strategyIntro: "¡Hola! Soy tu asesor de estrategia migratoria. Puedo ayudarte a comparar visas o entender plazos.",
    strategyPlaceholder: "Pregunta sobre K-1 vs CR-1, tiempos de proceso...",
    supportIntro: "¡Hola! Soy tu agente de soporte ImmiGuide. ¿Cómo puedo ayudarte?",
    changeDoc: "Cambiar Documento",
    removeFile: "Eliminar Archivo",
    yourRfeContent: "Tu Contenido RFE",
    fileSelected: "Archivo Seleccionado",
    analysisComplete: "Análisis Completo",
    responseDraft: "Borrador de Respuesta",
    disclaimer: "Siempre haga que un abogado revise este documento.",
    strategyDisclaimer: "ImmiGuide puede cometer errores. Verifique con un abogado.",
    caseNumber: "Número de Caso",
    findExpert: "Buscar Experto",
    filterSpecialty: "Filtrar por Especialidad",
    filterLanguage: "Filtrar por Idioma",
    verifiedExpert: "Experto Verificado",
    successRate: "Tasa de Éxito",
    reviews: "reseñas",
    startsAt: "Desde",
    bookConsult: "Reservar Consulta Gratis 15-min",
    rfeMatch: "Recomendado para su RFE",
    nextAvailable: "Próximo disponible",
    allSpecialties: "Todas las Especialidades",
    allLanguages: "Todos los Idiomas"
  },
  zh: {
    dashboard: "仪表板",
    formAssistant: "智能表单助手",
    rfeDecoder: "RFE 解码器",
    strategy: "策略顾问",
    marketplace: "专家市场",
    welcome: "欢迎回来, Mateo",
    managing: "正在管理您的 I-130 外籍亲属申请",
    caseTimeline: "案件时间轴追踪",
    onTrack: "正如预期",
    waitNormal: "我的等待时间正常吗？",
    dontWorry: "别担心：您的案件进展正常。",
    daysPending: "您已经等待了 {days} 天。",
    quickActions: "快速操作",
    continueForm: "继续表格 I-130",
    formDesc: "使用 AI 错误检查完成您的申请。",
    rfeTitle: "收到了 RFE？",
    rfeDesc: "上传您的 USCIS 信件。我们的 AI 将对其进行解码。",
    stratTitle: "策略顾问",
    stratDesc: "不确定下一步？咨询我们的 AI 策略师。",
    marketTitle: "寻找律师",
    marketDesc: "为您的案件联系经过审查的专家。",
    signOut: "退出",
    profile: "个人资料",
    supportAgent: "ImmiGuide 支持",
    online: "在线",
    typeMessage: "输入消息...",
    uploadDoc: "上传文档 (PDF/图片)",
    pasteRfe: "在此粘贴 RFE 文本",
    analyzeNow: "立即分析",
    decoding: "解码中...",
    highSeverity: "检测到严重案件",
    highSeverityDesc: "此 RFE 表明您的申请存在重大风险。我们要强烈建议咨询策略顾问。",
    draftResponse: "起草法律回复信",
    requiredEvidence: "所需证据",
    actionPlan: "行动计划",
    saveContinue: "保存并继续",
    whereLived: "您住在哪里？",
    physAddress: "实际居住地址历史",
    aiHelper: "ImmiGuide 智能助手",
    analyzeField: "正在分析字段上下文...",
    focusField: "聚焦某个字段以查看建议。",
    whatMean: "这是什么意思？",
    commonTraps: "常见陷阱",
    exampleAns: "示例回答",
    formHealth: "表格健康度",
    fieldsCompleted: "已完成字段",
    validationErrors: "验证错误",
    strategyIntro: "您好！我是您的移民策略顾问。我可以帮助您比较签证类型或了解时间表。",
    strategyPlaceholder: "询问关于 K-1 与 CR-1，处理时间...",
    supportIntro: "您好！我是 ImmiGuide 支持代理。今天怎么帮您？",
    changeDoc: "更改文档",
    removeFile: "删除文件",
    yourRfeContent: "您的 RFE 内容",
    fileSelected: "已选择文件",
    analysisComplete: "分析完成",
    responseDraft: "回复草稿",
    disclaimer: "请务必让持照律师审查此文件。",
    strategyDisclaimer: "ImmiGuide 可能会犯错。请与律师核实重要信息。",
    caseNumber: "案件号码",
    findExpert: "寻找专家",
    filterSpecialty: "按专业筛选",
    filterLanguage: "按语言筛选",
    verifiedExpert: "已验证专家",
    successRate: "成功率",
    reviews: "条评论",
    startsAt: "起价",
    bookConsult: "预订 15 分钟免费咨询",
    rfeMatch: "针对您的 RFE 推荐",
    nextAvailable: "下次可用",
    allSpecialties: "所有专业",
    allLanguages: "所有语言"
  },
  ar: {
    dashboard: "لوحة القيادة",
    formAssistant: "مساعد النماذج الذكي",
    rfeDecoder: "فك شفرة RFE",
    strategy: "مستشار الاستراتيجية",
    marketplace: "سوق الخبراء",
    welcome: "مرحباً بعودتك، ماتيو",
    managing: "إدارة التماس I-130 الخاص بك للقريب الأجنبي",
    caseTimeline: "متتبع الجدول الزمني للقضية",
    onTrack: "على المسار الصحيح",
    waitNormal: "هل وقت انتظاري طبيعي؟",
    dontWorry: "لا تقلق: قضيتك تسير بشكل طبيعي.",
    daysPending: "لقد كنت تنتظر {days} يوماً.",
    quickActions: "إجراءات سريعة",
    continueForm: "متابعة نموذج I-130",
    formDesc: "أكمل التماسك مع التحقق من الأخطاء المدعوم بالذكاء الاصطناعي.",
    rfeTitle: "هل تلقيت RFE؟",
    rfeDesc: "قم بتحميل خطاب USCIS الخاص بك. سيقوم الذكاء الاصطناعي بفك شفرته.",
    stratTitle: "المستشار الاستراتيجي",
    stratDesc: "غير متأكد من الخطوات التالية؟ اسأل مستشار الذكاء الاصطناعي لدينا.",
    marketTitle: "ابحث عن محام",
    marketDesc: "تواصل مع خبراء تم فحصهم لقضيتك المحددة.",
    signOut: "تسجيل الخروج",
    profile: "الملف الشخصي",
    supportAgent: "دعم ImmiGuide",
    online: "متصل",
    typeMessage: "اكتب رسالة...",
    uploadDoc: "تحميل مستند (PDF/صورة)",
    pasteRfe: "الصق نص RFE هنا",
    analyzeNow: "حلل الآن",
    decoding: "جاري فك التشفير...",
    highSeverity: "تم اكتشاف حالة عالية الخطورة",
    highSeverityDesc: "يشير هذا RFE إلى خطر كبير. نوصي بشدة باستشارة مستشار الاستراتيجية.",
    draftResponse: "صياغة خطاب الرد القانوني",
    requiredEvidence: "الأدلة المطلوبة",
    actionPlan: "خطة العمل",
    saveContinue: "حفظ ومتابعة",
    whereLived: "أين عشت؟",
    physAddress: "تاريخ العنوان الفعلي",
    aiHelper: "مساعد ImmiGuide الذكي",
    analyzeField: "تحليل سياق الحقل...",
    focusField: "ركز على حقل لرؤية النصائح المخصصة.",
    whatMean: "ماذا يعني هذا؟",
    commonTraps: "الفخاخ الشائعة",
    exampleAns: "مثال للإجابة",
    formHealth: "صحة النموذج",
    fieldsCompleted: "الحقول المكتملة",
    validationErrors: "أخطاء التحقق",
    strategyIntro: "مرحبًا! أنا مستشار استراتيجية الهجرة الخاص بك. يمكنني مساعدتك في مقارنة أنواع التأشيرات أو فهم الجداول الزمنية.",
    strategyPlaceholder: "اسأل عن K-1 مقابل CR-1، أو أوقات المعالجة...",
    supportIntro: "مرحبًا! أنا وكيل دعم ImmiGuide الخاص بك. كيف يمكنني مساعدتك اليوم؟",
    changeDoc: "تغيير المستند",
    removeFile: "إزالة الملف",
    yourRfeContent: "محتوى RFE الخاص بك",
    fileSelected: "تم تحديد الملف",
    analysisComplete: "اكتمل التحليل",
    responseDraft: "مسودة الرد",
    disclaimer: "اطلب دائمًا من محامٍ مرخص مراجعة هذا المستند.",
    strategyDisclaimer: "قد يرتكب ImmiGuide أخطاء. يرجى التحقق من المعلومات المهمة مع محام.",
    caseNumber: "رقم القضية",
    findExpert: "ابحث عن خبير",
    filterSpecialty: "تصفية حسب التخصص",
    filterLanguage: "تصفية حسب اللغة",
    verifiedExpert: "خبير معتمد",
    successRate: "معدل النجاح",
    reviews: "المراجعات",
    startsAt: "يبدأ في",
    bookConsult: "احجز استشارة مجانية لمدة 15 دقيقة",
    rfeMatch: "موصى به ل RFE الخاص بك",
    nextAvailable: "المتاح التالي",
    allSpecialties: "جميع التخصصات",
    allLanguages: "جميع اللغات"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
