import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

export const generateSummaryPDF = async (formData: any, formName: string) => {
  // Create a new PDFDocument
  const pdfDoc = await PDFDocument.create();
  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const timesBoldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);
  
  // Add a page
  let page = pdfDoc.addPage();
  const { width, height } = page.getSize();
  const fontSize = 11;
  const margin = 50;
  
  let yOffset = height - margin;

  // Title
  page.drawText(`${formName} - Data Summary`, {
    x: margin,
    y: yOffset,
    size: 18,
    font: timesBoldFont,
    color: rgb(0, 0.2, 0.4),
  });
  yOffset -= 30;

  // Subtitle/Timestamp
  page.drawText(`Generated by ImmiGuide on ${new Date().toLocaleDateString()}`, {
    x: margin,
    y: yOffset,
    size: 10,
    font: timesRomanFont,
    color: rgb(0.5, 0.5, 0.5),
  });
  yOffset -= 40;

  // Divider
  page.drawLine({
      start: { x: margin, y: yOffset + 10 },
      end: { x: width - margin, y: yOffset + 10 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
  });

  // Loop through data
  const entries = Object.entries(formData);
  
  for (const [key, value] of entries) {
      if (yOffset < margin) {
          page = pdfDoc.addPage();
          yOffset = height - margin;
      }

      // Label
      const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, (str) => str.toUpperCase());
      page.drawText(label + ':', {
        x: margin,
        y: yOffset,
        size: 10,
        font: timesBoldFont,
        color: rgb(0.3, 0.3, 0.3),
      });

      // Value
      const valText = String(value || 'N/A');
      page.drawText(valText, {
        x: margin + 150,
        y: yOffset,
        size: 11,
        font: timesRomanFont,
        color: rgb(0, 0, 0),
      });
      
      yOffset -= 25;
  }

  // Disclaimer Footer
  const disclaimerText = "DISCLAIMER: This document is a data summary generated by AI assistance. It is NOT an official USCIS form. Please transcribe this data onto the official form downloaded from uscis.gov.";
  page.drawText(disclaimerText, {
      x: margin,
      y: 30,
      size: 8,
      font: timesRomanFont,
      color: rgb(0.8, 0, 0)
  });

  // Serialize the PDFDocument to bytes (a Uint8Array)
  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}