import React, { useState } from 'react';
import { ShieldAlert, CheckCircle2, Lock, FileText, ArrowRight } from 'lucide-react';
import { LegalDocViewer } from './LegalDocViewer';

interface LegalModalProps {
    onAccept: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ onAccept }) => {
    const [scrolled, setScrolled] = useState(false);
    const [agreed, setAgreed] = useState(false);
    const [showFullDoc, setShowFullDoc] = useState<'privacy' | 'terms' | null>(null);

    const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
        const bottom = e.currentTarget.scrollHeight - e.currentTarget.scrollTop === e.currentTarget.clientHeight;
        if (bottom || e.currentTarget.scrollTop > 100) setScrolled(true);
    };

    return (
        <div className="fixed inset-0 z-[60] bg-slate-900/90 backdrop-blur-sm flex items-center justify-center p-4">
            {showFullDoc && (
                <LegalDocViewer docType={showFullDoc} onClose={() => setShowFullDoc(null)} />
            )}

            <div className="bg-white max-w-lg w-full rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-300">
                
                {/* Header */}
                <div className="bg-slate-50 p-6 border-b border-slate-200">
                    <div className="flex items-center gap-3 justify-center mb-4">
                        <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center">
                            <ShieldAlert className="w-6 h-6 text-red-600" />
                        </div>
                    </div>
                    <h2 className="text-xl font-bold text-center text-slate-900">Legal Disclaimer & Terms</h2>
                    <p className="text-center text-sm text-slate-500 mt-1">Please review before using Visa Guide AI.</p>
                </div>

                {/* Scrollable Content */}
                <div 
                    className="flex-1 overflow-y-auto p-6 text-sm text-slate-600 leading-relaxed space-y-4"
                    onScroll={handleScroll}
                >
                    <p className="font-bold text-slate-900">1. Not Legal Advice</p>
                    <p>
                        Visa Guide AI is an Artificial Intelligence platform, <strong className="text-red-600">NOT a law firm</strong>. We do not provide legal advice, representation, or attorney-client privilege. The information provided by our AI is for educational and informational purposes only.
                    </p>

                    <p className="font-bold text-slate-900">2. No Guarantee of Results</p>
                    <p>
                        USCIS policies change frequently. While we strive for accuracy, Visa Guide AI cannot guarantee the approval of any immigration petition. Use this tool at your own risk.
                    </p>

                    <p className="font-bold text-slate-900">3. Data Privacy (Local Storage)</p>
                    <p>
                        Currently, Visa Guide AI operates in a local-first mode. Your sensitive documents (passports, tax returns) are stored in your browser's local storage and processed securely via API. Clearing your browser cache will delete your saved data.
                    </p>

                    <p className="font-bold text-slate-900">4. User Responsibility</p>
                    <p>
                        You are responsible for reviewing all forms generated by this system before submission to government authorities. You certify that all information you provide is true and accurate.
                    </p>

                    <div className="pt-4 border-t border-slate-100">
                        <p className="text-xs font-bold text-slate-500 uppercase mb-2">Read Full Documents</p>
                        <div className="flex gap-4">
                            <button onClick={() => setShowFullDoc('privacy')} className="text-blue-600 hover:underline">Privacy Policy</button>
                            <button onClick={() => setShowFullDoc('terms')} className="text-blue-600 hover:underline">Terms of Service</button>
                        </div>
                    </div>
                </div>

                {/* Footer Actions */}
                <div className="p-6 bg-slate-50 border-t border-slate-200">
                    <label className="flex items-start gap-3 cursor-pointer mb-6 group">
                        <div className={`mt-0.5 w-5 h-5 rounded border flex items-center justify-center transition-colors ${agreed ? 'bg-blue-600 border-blue-600' : 'bg-white border-slate-300 group-hover:border-blue-400'}`}>
                            {agreed && <CheckCircle2 className="w-3.5 h-3.5 text-white" />}
                        </div>
                        <input 
                            type="checkbox" 
                            className="hidden" 
                            checked={agreed}
                            onChange={(e) => setAgreed(e.target.checked)}
                        />
                        <span className="text-sm text-slate-700 select-none">
                            I acknowledge that Visa Guide AI is AI-powered and not a substitute for legal counsel. I agree to the Terms of Service.
                        </span>
                    </label>

                    <button 
                        onClick={onAccept}
                        disabled={!agreed}
                        className="w-full py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-colors shadow-lg flex items-center justify-center gap-2"
                    >
                        Accept & Continue <ArrowRight className="w-4 h-4" />
                    </button>
                </div>
            </div>
        </div>
    );
};